[2024-10-07T02:45:48.744+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-07T02:45:48.753+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Nikita_Lapshin_random_forest.train_model scheduled__2024-10-06T01:00:00+00:00 [queued]>
[2024-10-07T02:45:48.758+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Nikita_Lapshin_random_forest.train_model scheduled__2024-10-06T01:00:00+00:00 [queued]>
[2024-10-07T02:45:48.758+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2024-10-07T02:45:48.767+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_model> on 2024-10-06 01:00:00+00:00
[2024-10-07T02:45:48.771+0000] {standard_task_runner.py:64} INFO - Started process 4065 to run task
[2024-10-07T02:45:48.773+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Nikita_Lapshin_random_forest', 'train_model', 'scheduled__2024-10-06T01:00:00+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/HW1.py', '--cfg-path', '/tmp/tmp4qel8009']
[2024-10-07T02:45:48.775+0000] {standard_task_runner.py:91} INFO - Job 95: Subtask train_model
[2024-10-07T02:45:48.801+0000] {task_command.py:426} INFO - Running <TaskInstance: Nikita_Lapshin_random_forest.train_model scheduled__2024-10-06T01:00:00+00:00 [running]> on host 22775caa7dfb
[2024-10-07T02:45:48.849+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Lapshin Nikita' AIRFLOW_CTX_DAG_ID='Nikita_Lapshin_random_forest' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-10-06T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-06T01:00:00+00:00'
[2024-10-07T02:45:48.849+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-07T02:45:48.863+0000] {s3.py:1422} INFO - Downloading source S3 file from Bucket mlops-1 with path random_forest/datasets/prepared_data.csv
[2024-10-07T02:45:48.868+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-10-07T02:45:48.868+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-10-07T03:02:29.366+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-07T03:02:29.374+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/HW1.py", line 111, in train_model
    s3_hook.load_bytes(pickle.dumps(model), key=model_path, bucket_name=BUCKET, replace=True)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 158, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 132, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1205, in load_bytes
    self._upload_file_obj(f, key, bucket_name, replace, encrypt, acl_policy)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1255, in _upload_file_obj
    client.upload_fileobj(
  File "/home/airflow/.local/lib/python3.10/site-packages/boto3/s3/inject.py", line 642, in upload_fileobj
    return future.result()
  File "/home/airflow/.local/lib/python3.10/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/home/airflow/.local/lib/python3.10/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/httpsession.py", line 464, in send
    urllib_response = conn.urlopen(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/awsrequest.py", line 96, in request
    rval = super().request(method, url, body, headers, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connection.py", line 399, in request
    for chunk in chunks:
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/util/request.py", line 226, in chunk_readable
    datablock = body.read(blocksize)
  File "/home/airflow/.local/lib/python3.10/site-packages/s3transfer/utils.py", line 520, in read
    data = self._fileobj.read(amount_to_read)
  File "/home/airflow/.local/lib/python3.10/site-packages/s3transfer/upload.py", line 90, in read
    raise self._transfer_coordinator.exception
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/httpsession.py", line 464, in send
    urllib_response = conn.urlopen(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/awsrequest.py", line 96, in request
    rval = super().request(method, url, body, headers, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connection.py", line 399, in request
    for chunk in chunks:
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/util/request.py", line 226, in chunk_readable
    datablock = body.read(blocksize)
  File "/home/airflow/.local/lib/python3.10/site-packages/s3transfer/utils.py", line 520, in read
    data = self._fileobj.read(amount_to_read)
  File "/home/airflow/.local/lib/python3.10/site-packages/s3transfer/upload.py", line 90, in read
    raise self._transfer_coordinator.exception
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/httpsession.py", line 464, in send
    urllib_response = conn.urlopen(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/awsrequest.py", line 96, in request
    rval = super().request(method, url, body, headers, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connection.py", line 399, in request
    for chunk in chunks:
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/util/request.py", line 226, in chunk_readable
    datablock = body.read(blocksize)
  File "/home/airflow/.local/lib/python3.10/site-packages/s3transfer/utils.py", line 520, in read
    data = self._fileobj.read(amount_to_read)
  File "/home/airflow/.local/lib/python3.10/site-packages/s3transfer/upload.py", line 90, in read
    raise self._transfer_coordinator.exception
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/httpsession.py", line 464, in send
    urllib_response = conn.urlopen(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/awsrequest.py", line 96, in request
    rval = super().request(method, url, body, headers, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connection.py", line 399, in request
    for chunk in chunks:
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/util/request.py", line 226, in chunk_readable
    datablock = body.read(blocksize)
  File "/home/airflow/.local/lib/python3.10/site-packages/s3transfer/utils.py", line 520, in read
    data = self._fileobj.read(amount_to_read)
  File "/home/airflow/.local/lib/python3.10/site-packages/s3transfer/upload.py", line 90, in read
    raise self._transfer_coordinator.exception
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/httpsession.py", line 464, in send
    urllib_response = conn.urlopen(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/awsrequest.py", line 96, in request
    rval = super().request(method, url, body, headers, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connection.py", line 399, in request
    for chunk in chunks:
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/util/request.py", line 226, in chunk_readable
    datablock = body.read(blocksize)
  File "/home/airflow/.local/lib/python3.10/site-packages/s3transfer/utils.py", line 520, in read
    data = self._fileobj.read(amount_to_read)
  File "/home/airflow/.local/lib/python3.10/site-packages/s3transfer/upload.py", line 90, in read
    raise self._transfer_coordinator.exception
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/httpsession.py", line 464, in send
    urllib_response = conn.urlopen(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/awsrequest.py", line 96, in request
    rval = super().request(method, url, body, headers, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connection.py", line 399, in request
    for chunk in chunks:
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/util/request.py", line 226, in chunk_readable
    datablock = body.read(blocksize)
  File "/home/airflow/.local/lib/python3.10/site-packages/s3transfer/utils.py", line 520, in read
    data = self._fileobj.read(amount_to_read)
  File "/home/airflow/.local/lib/python3.10/site-packages/s3transfer/upload.py", line 90, in read
    raise self._transfer_coordinator.exception
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/httpsession.py", line 464, in send
    urllib_response = conn.urlopen(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/awsrequest.py", line 96, in request
    rval = super().request(method, url, body, headers, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connection.py", line 399, in request
    for chunk in chunks:
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/util/request.py", line 226, in chunk_readable
    datablock = body.read(blocksize)
  File "/home/airflow/.local/lib/python3.10/site-packages/s3transfer/utils.py", line 520, in read
    data = self._fileobj.read(amount_to_read)
  File "/home/airflow/.local/lib/python3.10/site-packages/s3transfer/upload.py", line 90, in read
    raise self._transfer_coordinator.exception
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/httpsession.py", line 464, in send
    urllib_response = conn.urlopen(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/awsrequest.py", line 96, in request
    rval = super().request(method, url, body, headers, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connection.py", line 399, in request
    for chunk in chunks:
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/util/request.py", line 226, in chunk_readable
    datablock = body.read(blocksize)
  File "/home/airflow/.local/lib/python3.10/site-packages/s3transfer/utils.py", line 520, in read
    data = self._fileobj.read(amount_to_read)
  File "/home/airflow/.local/lib/python3.10/site-packages/s3transfer/upload.py", line 90, in read
    raise self._transfer_coordinator.exception
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/httpsession.py", line 464, in send
    urllib_response = conn.urlopen(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/awsrequest.py", line 96, in request
    rval = super().request(method, url, body, headers, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connection.py", line 399, in request
    for chunk in chunks:
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/util/request.py", line 226, in chunk_readable
    datablock = body.read(blocksize)
  File "/home/airflow/.local/lib/python3.10/site-packages/s3transfer/utils.py", line 520, in read
    data = self._fileobj.read(amount_to_read)
  File "/home/airflow/.local/lib/python3.10/site-packages/s3transfer/upload.py", line 90, in read
    raise self._transfer_coordinator.exception
  File "/home/airflow/.local/lib/python3.10/site-packages/s3transfer/tasks.py", line 139, in __call__
    return self._execute_main(kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/s3transfer/tasks.py", line 162, in _execute_main
    return_value = self._main(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/s3transfer/upload.py", line 793, in _main
    response = client.upload_part(
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/client.py", line 1021, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (RequestTimeTooSkewed) when calling the UploadPart operation: The difference between the request time and the current time is too large.
[2024-10-07T03:02:29.397+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Nikita_Lapshin_random_forest, task_id=train_model, run_id=scheduled__2024-10-06T01:00:00+00:00, execution_date=20241006T010000, start_date=20241007T024548, end_date=20241007T030229
[2024-10-07T03:02:29.424+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 95 for task train_model (An error occurred (RequestTimeTooSkewed) when calling the UploadPart operation: The difference between the request time and the current time is too large.; 4065)
[2024-10-07T03:02:29.492+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-10-07T03:02:29.529+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-07T03:02:29.530+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
